bump rebar3 to 3.14.3
erlang/docker-erlang-otp pull request #315
Opened 2020-12-02 15:27 UTC by tsloughter

2020-12-03 06:24 UTC, getong commented
https://travis-ci.org/github/erlang/docker-erlang-otp/jobs/747216096
is not passed, and it is not related to the changed code. But it is better to format the code as usual.

2020-12-03 13:41 UTC, tsloughter commented
Well damn... Do you understand what is wrong? I see the error is `The command "docker build --pull -t "$image" "${VARIANT:-.}"" exited with 127.`

2020-12-03 15:45 UTC, getong requested changes

2020-12-03 15:47 UTC, getong commented
> Well damn... Do you understand what is wrong? I see the error is `The command "docker build --pull -t "$image" "${VARIANT:-.}"" exited with 127.`

It might be something network wrong, you can make a new commit, and make the ci build again. I do not have the priviledge to make the ci build again.

2020-12-03 15:47 UTC, tsloughter commented on 23/Dockerfile
> +    && REBAR3_DOWNLOAD_URL="https://github.com/erlang/rebar3/archive/${REBAR3_VERSION}.tar.gz" \
oh dammit, my emacs must be doing that. I thought I caught it and replaced with a tab.

2020-12-03 15:49 UTC, tsloughter commented on 23/Dockerfile
> +    && REBAR3_DOWNLOAD_URL="https://github.com/erlang/rebar3/archive/${REBAR3_VERSION}.tar.gz" \
Fixed.

2020-12-03 16:39 UTC, tsloughter commented
Looks like travis is stuck queued... hopefully it goes through soon.

2020-12-03 20:38 UTC, tsloughter commented
@getong looks like it'll finish this time.

You then send a PR to a docker repo, right? Is there a script that generates that patch or do you manually make the changes and send?

2020-12-04 08:37 UTC, merged

2020-12-04 09:14 UTC, getong commented
I do it manually:
```
./generate-stackbrew-library.sh > ../official-images/library/erlang
```
and then open a pr.